# Generated by Django 4.1.2 on 2022-10-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filum', models.CharField(max_length=9)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='seafood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('kingdom', models.CharField(max_length=50)),
                ('kelas', models.CharField(max_length=40)),
                ('ordo', models.CharField(max_length=40)),
                ('famili', models.CharField(max_length=40)),
                ('genus', models.CharField(max_length=40)),
            ],
        ),
    ]
