# Generated by Django 4.1.2 on 2022-10-29 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seafoodapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seafood',
            name='famili',
        ),
        migrations.RemoveField(
            model_name='seafood',
            name='genus',
        ),
        migrations.RemoveField(
            model_name='seafood',
            name='ordo',
        ),
        migrations.AddField(
            model_name='seafood',
            name='filum_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seafoodapp.kelompok'),
        ),
        migrations.AlterField(
            model_name='kelompok',
            name='filum',
            field=models.CharField(max_length=20),
        ),
    ]
