# Generated by Django 4.1.2 on 2022-10-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafoodapp', '0002_remove_seafood_famili_remove_seafood_genus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seafood',
            name='detail',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='seafood',
            name='image',
            field=models.ImageField(null=True, upload_to='static'),
        ),
    ]
