# Generated by Django 4.1.2 on 2022-10-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafoodapp', '0004_alter_seafood_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seafood',
            name='detail',
            field=models.URLField(max_length=100),
        ),
    ]
